/*
 * meta.h - C++20 Serialization Framework
 *
 * This test file was automatically generated by Claude UI to demonstrate
 * the capabilities and features of the meta.h C++20 serialization framework.
 */

#include <iostream>

#include "meta.h"

using namespace meta;
// Simple struct with fields
struct Person {
  std::string name;
  int age;
  bool active;

  // Define fields as tuple
  static constexpr auto FieldsMeta = std::tuple(
      field<&Person::name>("name", Description{"Person's name"}),
      field<&Person::age>("age", Description{"Person's age"}),
      field<&Person::active>("active", Description{"Is person active"}));
};

int main() {
  // Create YAML
  YAML::Node yaml = YAML::Load(R"(
    name: Alice
    age: 30
    active: true
  )");

  // Parse from YAML

  auto [person, result] = meta::reifyFromYaml<Person>(yaml);

  if (person) {
    std::cout << "=== toString ===\n" << meta::toString(*person) << "\n";
    std::cout << "=== toJson ===\n" << meta::toJson(*person) << "\n";

    auto yaml = meta::toYaml(*person);
    std::cout << "=== toYaml ===\n";
    std::cout << yaml << "\n";
  }

  return 0;
}
