/*
 * meta.h - C++20 Serialization Framework
 *
 * This test file was automatically generated by Claude UI to demonstrate
 * the capabilities and features of the meta.h C++20 serialization framework.

 */

#include <iostream>
#include <sstream>
#include <string>

#include "meta.h"
#include "meta_csv.h"

using namespace meta;

// ============================================================================
// EXAMPLE STRUCTURES
// ============================================================================

struct Person {
  std::string name;
  int age;
  std::string email;
  std::vector<std::string> hobbies;

  static constexpr auto fields = std::make_tuple(
      field<&Person::name>("name", Description{"Person's name"}),
      field<&Person::age>("age", Description{"Person's age"}),
      field<&Person::email>("email", Description{"Email address"}),
      field<&Person::hobbies>("hobbies", Description{"List of hobbies"}));
};

struct Company {
  std::string name;
  int employees;
  double revenue;
  std::map<std::string, int> departments;

  static constexpr auto fields = std::make_tuple(
      field<&Company::name>("name", Description{"Company name"}),
      field<&Company::employees>("employees",
                                     Description{"Number of employees"}),
      field<&Company::revenue>("revenue", Description{"Annual revenue"}),
      field<&Company::departments>("departments",
                                       Description{"Department counts"}));
};

struct Config {
  std::string appName;
  int timeout;
  bool debug;
  std::vector<int> ports;
  std::optional<std::string> description;

  static constexpr auto fields = std::make_tuple(
      field<&Config::appName>("appName", Description{"App name"}),
      field<&Config::timeout>("timeout", Description{"Timeout in seconds"}),
      field<&Config::debug>("debug", Description{"Debug mode"}),
      field<&Config::ports>("ports", Description{"Listening ports"}),
      field<&Config::description>("description",
                                      Description{"Optional description"}));
};

// ============================================================================
// MAIN - Demonstrate CSV from meta.h serializer
// ============================================================================

int main() {
  std::cout << "     CSV Output Using meta.h Serializer \n";

  // ========================================
  // Example 1: Simple Struct
  // ========================================
  std::cout << "--- Example 1: Simple Struct ---\n";

  Person person{"Alice Johnson",
                28,
                "alice@example.com",
                {"reading", "coding", "hiking"}};
  std::cout << "Header: " << meta::toCSVHeader<Person>() << "\n";
  std::cout << "Data:   " << meta::toCSV(person) << "\n\n";

  // ========================================
  // Example 2: Multiple Simple Structs
  // ========================================
  std::cout << "--- Example 2: Multiple People ---\n";

  std::vector<Person> people = {
      {"Bob Smith", 35, "bob@example.com", {"sports", "travel"}},
      {"Carol White",
       42,
       "carol@example.com",
       {"gardening", "cooking", "painting"}},
      {"Dave Brown", 31, "dave@example.com", {}}};

  std::cout << meta::toCSVHeader<Person>() << "\n";
  for (const auto &p : people) {
    std::cout << meta::toCSV(p) << "\n";
  }
  std::cout << "\n";

  // ========================================
  // Example 3: Struct with Maps
  // ========================================
  std::cout << "--- Example 3: Struct with Maps ---\n";

  Company company{
      "TechCorp",
      150,
      5000000.0,
      {{"Engineering", 60}, {"Sales", 50}, {"HR", 20}, {"Operations", 20}}};

  std::cout << "Header: " << meta::toCSVHeader<Company>() << "\n";
  std::cout << "Data:   " << meta::toCSV(company) << "\n\n";

  // ========================================
  // Example 4: Struct with Vectors and Optional
  // ========================================
  std::cout << "--- Example 4: Config with Optional ---\n";

  Config cfg1{"WebApp", 30, true, {80, 443, 8080}, "Production server"};
  Config cfg2{"Worker", 60, false, {9000}, std::nullopt};

  std::cout << "Header: " << meta::toCSVHeader<Config>() << "\n";
  std::cout << "Cfg 1:  " << meta::toCSV(cfg1) << "\n";
  std::cout << "Cfg 2:  " << meta::toCSV(cfg2) << "\n\n";

  // ========================================
  // Example 5: Comparison - YAML vs CSV
  // ========================================
  std::cout << "--- Example 5: Same Data in Different Formats ---\n";

  Person p{"Eve Davis", 26, "eve@example.com", {"writing", "photography"}};

  std::cout << "YAML:\n" << meta::toYaml(p) << "\n";
  std::cout << "JSON:\n" << meta::toJson(p) << "\n";
  std::cout << "CSV:\n"
            << meta::toCSVHeader<Person>() << "\n"
            << meta::toCSV(p) << "\n\n";

  return 0;
}
