/*
 * meta.h - C++20 Serialization Framework
 * This test file was automatically generated by Claude UI to demonstrate
 * the capabilities and features of the meta.h C++20 serialization framework.
 */

#include <iostream>

#include "meta.h"
using namespace meta;

struct Config {
  std::string title;
  std::map<std::string, std::string> settings;
  std::vector<std::string> tags;
  double timeout;

  static constexpr auto FieldsMeta = std::make_tuple(
      field<&Config::title>("title", Description{"Config title"}),
      field<&Config::settings>("settings",
                                   Description{"Key-value settings"}),
      field<&Config::tags>("tags", Description{"Tag list"}),
      field<&Config::timeout>("timeout",
                                  Description{"Timeout in seconds"}));
};

int main() {
  YAML::Node yaml = YAML::Load(R"(
title: MyApp
settings:
  color: blue
  mode: debug
tags:
  - important
  - production
timeout: 30.5
)");

  auto [config, result] = meta::reifyFromYaml<Config>(yaml);
  if (result.valid && config) {
    std::cout << meta::toString(*config);
    std::cout << "\n=== JSON ===\n" << meta::toJson(*config);
  }

  std::cout << "\n";
  return 0;
}
