/*
 * meta.h - C++20 Serialization Framework
 *
 * This test file was automatically generated by Claude UI to demonstrate
 * the capabilities and features of the meta.h C++20 serialization framework.
 */

#include <iostream>
#include <tuple>

#include "meta.h"

using namespace meta;
// ============================================================================
// TEST: Tuples in Structs
// ============================================================================

struct Coordinate {
  std::string name;
  std::tuple<double, double, double> position; // x, y, z

  static constexpr auto fields = std::make_tuple(
      field<&Coordinate::name>("name", Description{"Coordinate name"}),
      field<&Coordinate::position>("position",
                                       Description{"XYZ position"}));
};

struct Building {
  std::string address;
  std::tuple<int, int> dimensions;                 // width, height
  std::vector<std::tuple<std::string, int>> rooms; // name, floor

  static constexpr auto fields = std::make_tuple(
      field<&Building::address>("address", Description{"Building address"}),
      field<&Building::dimensions>("dimensions",
                                       Description{"Width and height"}),
      field<&Building::rooms>(
          "rooms", Description{"Rooms with their floor numbers"}));
};

int main() {
  std::cout << "============================================================\n";
  std::cout << "TEST: Tuples in Structs\n";
  std::cout
      << "============================================================\n\n";

  // ========== Test 1: Simple tuple in struct ==========
  std::cout
      << "--- Test 1: Coordinate with tuple<double, double, double> ---\n";
  Coordinate coord{"Point A", {10.5, 20.3, 15.7}};

  std::cout << "Original (YAML):\n" << meta::toYaml(coord);
  std::cout << "\nOriginal (JSON):\n" << meta::toJson(coord) << "\n\n";

  // Deserialize coordinate
  std::string coord_yaml = R"(
name: Point B
position: [5.2, 10.1, 3.8]
)";

  YAML::Node coord_node = YAML::Load(coord_yaml);
  auto [coord_deser, coord_result] =
      meta::reifyFromYaml<Coordinate>(coord_node);

  if (coord_result.valid && coord_deser) {
    std::cout << " Coordinate deserialization successful!\n";
    std::cout << "  Name: " << coord_deser->name << "\n";
    std::cout << "  Position: (" << std::get<0>(coord_deser->position) << ", "
              << std::get<1>(coord_deser->position) << ", "
              << std::get<2>(coord_deser->position) << ")\n\n";
  } else {
    std::cout << " Coordinate deserialization failed:\n";
    for (const auto &[field, err] : coord_result.errors) {
      std::cout << "  " << field << ": " << err << "\n";
    }
    std::cout << "\n";
  }

  // ========== Test 2: Multiple tuples in struct ==========
  std::cout << "--- Test 2: Building with tuple<int, int> and "
               "vector<tuple<string, int>> ---\n";
  Building building{
      "123 Main St",
      {100, 50},
      {{"lobby", 1}, {"office-a", 2}, {"office-b", 2}, {"penthouse", 3}}};

  std::cout << "Original (YAML):\n" << meta::toYaml(building);
  std::cout << "\nOriginal (JSON):\n" << meta::toJson(building) << "\n\n";

  // Deserialize building
  std::string building_yaml = R"(
address: 456 Oak Ave
dimensions: [200, 75]
rooms:
  - [entry, 1]
  - [kitchen, 1]
  - [bedroom-a, 2]
  - [bedroom-b, 2]
  - [master, 3]
)";

  YAML::Node building_node = YAML::Load(building_yaml);
  auto [building_deser, building_result] =
      meta::reifyFromYaml<Building>(building_node);

  if (building_result.valid && building_deser) {
    std::cout << " Building deserialization successful!\n";
    std::cout << "  Address: " << building_deser->address << "\n";
    std::cout << "  Dimensions: " << std::get<0>(building_deser->dimensions)
              << "" << std::get<1>(building_deser->dimensions) << "\n";
    std::cout << "  Rooms:\n";
    for (size_t i = 0; i < building_deser->rooms.size(); ++i) {
      const auto &room = building_deser->rooms[i];
      std::cout << "   [" << i << "] " << std::get<0>(room) << " (Floor "
                << std::get<1>(room) << ")\n";
    }
  } else {
    std::cout << " Building deserialization failed:\n";
    for (const auto &[field, err] : building_result.errors) {
      std::cout << "  " << field << ": " << err << "\n";
    }
  }

  std::cout
      << "\n============================================================\n";
  std::cout << "Tuple tests completed!\n";
  std::cout << "============================================================\n";

  return 0;
}
