/*
 * meta.h - C++20 Serialization Framework
 *
 * This test file was automatically generated by Claude UI to demonstrate
 * the capabilities and features of the meta.h C++20 serialization framework.
 */

#include <iostream>

#include "meta.h"

// Simple struct with fields
struct Person
{
    std::string name;
    int age;
    bool active;

    // Define fields as tuple
    static constexpr auto fields =
        std::tuple{meta::Field<&Person::name>("name", "Person's name"),
                   meta::Field<&Person::age>("age", "Person's age"),
                   meta::Field<&Person::active>("active", "Is person active")};
};

int main()
{
    // Create YAML
    YAML::Node yaml = YAML::Load(R"(
    name: Alice
    age: 30
    active: true
  )");

    // Parse from YAML

    auto [person, result] = meta::reifyFromYaml<Person>(yaml);

    if (person)
    {
        std::cout << "=== toString ===\n" << meta::toString(*person) << "\n";
        std::cout << "=== toJson ===\n" << meta::toJson(*person) << "\n";

        auto yaml = meta::toYaml(*person);
        std::cout << "=== toYaml ===\n";
        std::cout << yaml << "\n";
    }

    return 0;
}
