/*
 * test_meta_yaml.cpp - Test Suite for meta_yaml.h
 * 
 * Generated by Claude UI to test the minimal YAML serialization framework
 */

#include "meta_yaml.h"
#include <iostream>
#include <cassert>

// ============================================================================
// TEST STRUCTS
// ============================================================================

struct Person {
    std::string name;
    int age;

    static constexpr auto fields = std::tuple{
        meta::Field<&Person::name>{"name"},
        meta::Field<&Person::age>{"age"}
    };
};

struct Address {
    std::string street;
    std::string city;

    static constexpr auto fields = std::tuple{
        meta::Field<&Address::street>{"street"},
        meta::Field<&Address::city>{"city"}
    };
};

struct Company {
    std::string name;
    std::vector<Person> employees;
    std::map<std::string, int> departments;
    std::optional<Address> headquarters;

    static constexpr auto fields = std::tuple{
        meta::Field<&Company::name>{"name"},
        meta::Field<&Company::employees>{"employees"},
        meta::Field<&Company::departments>{"departments"},
        meta::Field<&Company::headquarters>{"headquarters", meta::OptionalField}
    };
};

// ============================================================================
// TESTS
// ============================================================================

void test_primitive_int() {
    std::cout << "=== Test 1: Primitive Int ===" << std::endl;
    
    int val = 42;
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    int result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result == 42);
    
    std::cout << "✓ Int test passed\n" << std::endl;
}

void test_primitive_string() {
    std::cout << "=== Test 2: Primitive String ===" << std::endl;
    
    std::string val = "Hello World";
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::string result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result == "Hello World");
    
    std::cout << "✓ String test passed\n" << std::endl;
}

void test_primitive_bool() {
    std::cout << "=== Test 3: Primitive Bool ===" << std::endl;
    
    bool val = true;
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    bool result = false;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result == true);
    
    std::cout << "✓ Bool test passed\n" << std::endl;
}

void test_primitive_double() {
    std::cout << "=== Test 4: Primitive Double ===" << std::endl;
    
    double val = 3.14159;
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    double result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result > 3.1 && result < 3.2);
    
    std::cout << "✓ Double test passed\n" << std::endl;
}

void test_vector() {
    std::cout << "=== Test 5: Vector ===" << std::endl;
    
    std::vector<int> val = {1, 2, 3, 4, 5};
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::vector<int> result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.size() == 5);
    assert(result[0] == 1);
    assert(result[4] == 5);
    
    std::cout << "✓ Vector test passed\n" << std::endl;
}

void test_map() {
    std::cout << "=== Test 6: Map ===" << std::endl;
    
    std::map<std::string, int> val = {{"one", 1}, {"two", 2}, {"three", 3}};
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized:\n" << node << std::endl;
    
    std::map<std::string, int> result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.size() == 3);
    assert(result["one"] == 1);
    assert(result["two"] == 2);
    
    std::cout << "✓ Map test passed\n" << std::endl;
}

void test_optional_has_value() {
    std::cout << "=== Test 7: Optional (Has Value) ===" << std::endl;
    
    std::optional<int> val = 42;
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::optional<int> result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.has_value());
    assert(result.value() == 42);
    
    std::cout << "✓ Optional (has value) test passed\n" << std::endl;
}

void test_optional_null() {
    std::cout << "=== Test 8: Optional (Null) ===" << std::endl;
    
    std::optional<int> val = std::nullopt;
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::optional<int> result = 99;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(!result.has_value());
    
    std::cout << "✓ Optional (null) test passed\n" << std::endl;
}

void test_pair() {
    std::cout << "=== Test 9: Pair ===" << std::endl;
    
    std::pair<std::string, int> val = {"answer", 42};
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::pair<std::string, int> result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.first == "answer");
    assert(result.second == 42);
    
    std::cout << "✓ Pair test passed\n" << std::endl;
}

void test_tuple() {
    std::cout << "=== Test 10: Tuple ===" << std::endl;
    
    std::tuple<std::string, int, bool> val = {"test", 123, true};
    auto node = meta::dispatchSer(val);
    std::cout << "Serialized: " << node << std::endl;
    
    std::tuple<std::string, int, bool> result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(std::get<0>(result) == "test");
    assert(std::get<1>(result) == 123);
    assert(std::get<2>(result) == true);
    
    std::cout << "✓ Tuple test passed\n" << std::endl;
}

void test_simple_struct() {
    std::cout << "=== Test 11: Simple Struct (Person) ===" << std::endl;
    
    Person john{"John Doe", 30};
    auto node = meta::dispatchSer(john);
    std::cout << "Serialized:\n" << node << std::endl;
    
    Person result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.name == "John Doe");
    assert(result.age == 30);
    
    std::cout << "✓ Simple struct test passed\n" << std::endl;
}

void test_nested_struct() {
    std::cout << "=== Test 12: Nested Struct (Company) ===" << std::endl;
    
    Company acme{
        "ACME Corp",
        {
            {"Alice", 28},
            {"Bob", 35},
            {"Charlie", 42}
        },
        {
            {"Engineering", 50},
            {"Sales", 30}
        },
        Address{"123 Main St", "Springfield"}
    };
    
    auto node = meta::dispatchSer(acme);
    std::cout << "Serialized:\n" << node << std::endl;
    
    Company result;
    auto desResult = meta::dispatchDeser(result, meta::Node(node));
    assert(desResult.valid);
    assert(result.name == "ACME Corp");
    assert(result.employees.size() == 3);
    assert(result.employees[0].name == "Alice");
    assert(result.departments["Engineering"] == 50);
    assert(result.headquarters.has_value());
    assert(result.headquarters->city == "Springfield");
    
    std::cout << "✓ Nested struct test passed\n" << std::endl;
}

void test_yaml_roundtrip() {
    std::cout << "=== Test 13: YAML Roundtrip ===" << std::endl;
    
    Person john{"John Doe", 30};
    std::string yaml = meta::toYaml(john);
    std::cout << "Serialized YAML:\n" << yaml << std::endl;
    
    auto [person, result] = meta::fromYaml<Person>(yaml);
    assert(result.valid);
    assert(person.has_value());
    assert(person->name == "John Doe");
    assert(person->age == 30);
    
    std::cout << "✓ YAML roundtrip test passed\n" << std::endl;
}

void test_validation_error() {
    std::cout << "=== Test 14: Validation Error ===" << std::endl;
    
    std::string invalidYaml = R"(
name: Test
age: not_a_number
)";
    
    auto [person, result] = meta::fromYaml<Person>(invalidYaml);
    
    if (!result.valid) {
        std::cout << "Validation correctly detected errors:" << std::endl;
        for (const auto &[field, error] : result.errors) {
            std::cout << "  Field: " << (field.empty() ? "(root)" : field) 
                      << " Error: " << error << std::endl;
        }
        std::cout << "✓ Validation error test passed\n" << std::endl;
    } else {
        std::cout << "✗ Validation error test FAILED - should have caught error\n" << std::endl;
    }
}

// ============================================================================
// MAIN
// ============================================================================

int main() {
    std::cout << "\n╔════════════════════════════════════════════════════════════╗" << std::endl;
    std::cout << "║  meta_yaml.h - Minimal YAML Serialization Framework Tests  ║" << std::endl;
    std::cout << "╚════════════════════════════════════════════════════════════╝\n" << std::endl;

    try {
        test_primitive_int();
        test_primitive_string();
        test_primitive_bool();
        test_primitive_double();
        test_vector();
        test_map();
        test_optional_has_value();
        test_optional_null();
        test_pair();
        test_tuple();
        test_simple_struct();
        test_nested_struct();
        test_yaml_roundtrip();
        test_validation_error();

        std::cout << "\n╔════════════════════════════════════════════════════════════╗" << std::endl;
        std::cout << "║  ✓ ALL TESTS PASSED                                        ║" << std::endl;
        std::cout << "╚════════════════════════════════════════════════════════════╝\n" << std::endl;
        
        return 0;
    } catch (const std::exception &e) {
        std::cerr << "✗ Test failed with exception: " << e.what() << std::endl;
        return 1;
    }
}
